module.exports = {
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  GET_USER_BY_EMAIL: 'GET_USER_BY_EMAIL',
  GET_LOCATION: 'GET_LOCATION',
  GET_COUNTRIES: 'GET_COUNTRIES',
  GET_STATES: 'GET_STATES',
  GET_CITIES: 'GET_CITIES',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
};
