export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const ADD_DISH = 'ADD_DISH';
export const SET_DISHES = 'SET_DISHES';
export const UPDATE_DISH = 'UPDATE_DISH';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';
